### PR TITLE
Merged branches PR

### PR DESCRIPTION
**Pull request by stefanuebe**
@dg0s 

I test-merged all the PRs and ran into merge conflicts. If you want to merge in all my today's changes without having to go through yourself (just some minor issues, but issues), you may also simply merge this PR and reject all the others. 

This one also has all the new features as part of the demo enabled.

### CODE REVIEW

**Comment by dg0s** [comment]
> @dg0s
> 
> I test-merged all the PRs and ran into merge conflicts. If you want to merge in all my today's changes without having to go through yourself (just some minor issues, but issues), you may also simply merge this PR and reject all the others.
> 
> This one also has all the new features as part of the demo enabled.

Thank you very much @stefanuebe. I will review the changes ASAP. The upgrade is compliant with vaadin 14 or I need to release a new version just for vaadin 22?

**Comment by stefanuebe** [comment]
It's all built and tested with 14.8.3 and should in theory also work with 22

**Comment by stefanuebe** [comment]
Merged PR #16 into this one.

**Comment by stefanuebe** [comment]
Hi, any idea when you are able to review the changes and update the addon? We'd need it in the near future.

**Pull request merged**
